# Generated by Django 5.0.2 on 2024-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_book', '0003_alter_ingredient_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yield_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
